### ISSUE TITLE
Discuss Proposed - 0019-new-kademlia-routing-logic

### ISSUE THREAD

**Issue by Fraser999** [maidsafe/rfcs#86]
https://github.com/maidsafe/rfcs/blob/master/proposed/0019-new-kademlia-routing-logic/0019-new-kademlia-routing-logic.md

**Comment by Fraser999** [comment]
Not a big issue, but you have stated

> They each individually send their endpoints to the new node. The node replies with its own endpoints and establishes the connections.

With the previous code, most attempts would not have been agreed to by the recipient since it wouldn't have wanted the originator in its routing table.  Since now the connection attempt *must* be agreed to (assuming it's non-malicious, etc.) we can reduce the complexity of Routing here possibly.

So it would seem that the originator can just send its endpoints with the original request, rather than waiting to hear back from the recipient before sending its own endpoints?

**Comment by afck** [comment]
That's true.

Also, I think the members of the `NodeManager` that receives the `GetCloseGroup` request here should _not_ have to respond individually: They all know exactly the close group of the destination address since they are a member of it, so they can actually reply as the `NodeManager` and send identical responses containing all the close group's endpoints.

I'm still a bit confused by all the message types in Routing, but I'll try to make this part of the RFC more precise ...

**Comment by afck** [comment]
Actually, with the new Crust API and hole-punching, the members of that group won't be able to respond with actual endpoints, because those will have to contain the prepared contact infos, right?

So the close group will only respond with the public IDs, and then the endpoints will be sent and the connections established individually.

**Comment by Fraser999** [comment]
Yes, after posting I realised that we're sending individual messages so we can encrypt the endpoints.  Each message containing a node's endpoints is encrypted by the sender for the receiver, and I don't think we want to change that.

Also, I just noticed that the generated docs for the `GetPublicIdWithEndpoints` variant is wrong.  The encrypted endpoints contained in there aren't your endpoints - they're those of a peer which has agreed to try to connect to you.  We add its endpoints to that message so we don't have to hold onto them in some sort of LRU cache.  When the response to `GetPublicIdWithEndpoints` arrives, it contains these same encrypted endpoints (unchanged and useless to the group dealing with this request since they can't decrypt them) along with the `PublicId` of the peer.  We can then verify the peer is as claimed and we begin to connect at the Crust level then.

So we probably *do* want to do what is in the RFC more or less, but I think we should discuss the details of the new flow elsewhere to avoid cluttering this issue.

**Comment by afck** [comment]
Actually, I think most of the connection flow is actually not even related to this RFC. I propose changing it so that we really just send `GetCloseGroup`: #87 
Once we know the individual members of the close group, we start connecting to them as usual.

**Comment by Fraser999** [comment]
Yes, I think avoiding discussing the flow in detail in this RFC is a good plan, but your proposed changes tie in with what I was thinking more or less.

**Comment by dirvine** [comment]
:+1:

**Comment by Fraser999** [comment]
In [Changes to the routing logic](https://github.com/maidsafe/rfcs/blob/master/proposed/0019-new-kademlia-routing-logic/0019-new-kademlia-routing-logic.md#changes-to-the-routing-logic) you have:

> I am allowed to connect to you (and learn about your IP address) if and only if you are in the close group of one of my bucket addresses: an address that differs from mine in exactly one bit, (independent of whether you want me in your routing table).

under the "In routing" section, but shouldn't this be part of the second bullet of the "In kademlia_routing_table" section?

**Comment by afck** [comment]
I had it in "routing" because it affects the `want_address_in_routing_table` method - but that logic should indeed move into the kademlia_routing_table crate.

I don't think it's identical to the second point, though: `want_to_add` returns whether I need you in my routing table so that the invariant is satisfied in my node. This point, however, is about whether I allow you to add me to your routing table, even if I don't strictly need you in mine - this will happen occasionally whenever some branch of the address tree is not perfectly balanced.

**Comment by afck** [comment]
I added PR #88 for this.

**Comment by Fraser999** [comment]
Yes - I didn't mean it was an identical point - just that it belonged in the same bullet that talked about updating the `add_node` and `want_to_add` functions.

So, another point... :)

[Property 2](https://github.com/maidsafe/rfcs/blob/master/proposed/0019-new-kademlia-routing-logic/0019-new-kademlia-routing-logic.md#property-2) states "`m` has `n` in its routing table. *Therefore, the two are connected.*" (emphasis mine).  I'm not sure we've stated anywhere that an entry in the RT guarantees that there's a connection.  Certainly that's not what we have currently.

We allow addition of close peers to the RT even though we can't connect to them.  Swarm messages were intended to support message delivery to these "partially-connected" nodes, and churn messages would notify a node that such a peer had gone offline, since it wouldn't receive a notification from Crust.

Do we need to add that a RT entry implies a usable connection between the peers as an invariant?  Or at least where the peers are close together.

**Comment by afck** [comment]
Ah, I wasn't aware that we currently allow that.

The whole RFC doesn't deal with individual failing connections yet. It's just an attempt to improve the current implementation, so that at least under _ideal conditions_, i. e. with no failing connections and with only slowly joining and leaving nodes, a few necessary properties are guaranteed. So the assumption here is that nodes can always connect to each other. And I'm afraid this assumption is necessary to prove several of the properties.

I think we should deal with impossible connections in a separate RFC, and explicitly handle them: E. g. if I need A in my routing table but can't connect to it, I need to find a specialised proxy node for it, that is, a node B which can connect to both of us. The information about B should be stored in the `NodeInfo` of A, to fix the issue in a way that is transparent to the abstract Kademlia logic.
And that would need to be done for _every_ failing connection, not just for the ones close to ourselves. (I think that the notion of being in our close group is not really very relevant; this is also why we need to change the churn process: What really matters in many cases is whether there exists _any_ address such that we and the other node are both in that address' close group.)

**Comment by Fraser999** [comment]
> I think we should deal with impossible connections in a separate RFC

I agree.  And I've just noticed that you do indeed cover the connections point in the original list of guaranteed properties.

**Comment by rossmuir** [comment]
Implemented > https://github.com/maidsafe/rfcs/tree/master/implemented/0019-new-kademlia-routing-logic
